services:
    db:
        image: mongo
        container_name: db
        ports:
            - '27017:27017'
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
    web:
        build:
            context: .
            dockerfile: Dockerfile
            network: host
        container_name: web
        depends_on:
            - db
        environment:
            - PORT=5000
            - NODE_ENV=development
        ports:
            - '80:5000'
        volumes:
            - .:/app

volumes:
    mongodb:
    mongodb_config:
