services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            network: host
        container_name: web
        environment:
            - PORT=5000
            - NODE_ENV=development
        ports:
            - '80:5000'
        volumes:
            - .:/app
